### ISSUE TITLE
Default Account Naming Conventions (create + import)

### ISSUE THREAD

**Issue by anjj123** [GetSpeckle/speckle-browser-extension#51]
If user doesnt type in an account name on creation or import, we need the wallet to assign a default name that increments sequentially and doesn't duplicate (such as Account 1, Account 2 etc)

**Comment by fyang1024** [comment]
@anjj123 please check out the latest master and test it. The default account name should be Account N, where N is the number of current accounts plus 1. Say, if you have accounts `cool`, `anjj123` already, when you create an account or import an account by phrase, the default name will be `Account 3`. 

 If you import keystore file, no default account name will be assigned, as keystore file usually has name already. Even if it does not have name already, no default name will be generated to avoid surprise (User did not see it when importing)
