### ISSUE TITLE
White corners on extension 

### ISSUE THREAD

**Issue by anjj123** [GetSpeckle/speckle-browser-extension#59]
There are white corners on the extension that aren't viewable on other extensions

![Screen Shot 2019-05-06 at 10 18 11 pm](https://user-images.githubusercontent.com/39804936/57224385-a5067500-704c-11e9-9137-bb4e81ba3259.png)

**Comment by fyang1024** [comment]
<img width="903" alt="Screen Shot 2019-05-14 at 9 31 26 pm" src="https://user-images.githubusercontent.com/20808865/57694669-af99bd80-768f-11e9-836a-7f0280da5635.png">
@anjj123 it seems from the background image. You'll need to ask designers to change the SVG file

**Comment by anjj123** [comment]
Good catch. Looks like it was designed to be rounded, rather than squared. Ill fix this up asap
